spring:
  data:
    rest:
      detection-strategy: "annotated" # Stops spring-data-rest auto-config of entities controllers
  # datasource: # Use db profiles for configuration i.e. h2, mysql, etc.

server:
  compression:
    enabled: true
    mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json"
    min-response-size: 2048
