spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:mydb
    # url: jdbc:h2:file:/data/demo;DB_CLOSE_DELAY = -1 # file based
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console
  jpa:
    defer-datasource-initialization: true # true, false if we use flyway or liquibase or schema.sql