spring:
  data:
    rest:
      detection-strategy: "annotated" # Stops spring-data-rest auto-config of entities controllers
  datasource:
    url: jdbc:h2:mem:mydb # in memory
    # url: jdbc:h2:file:/data/demo;DB_CLOSE_DELAY = -1 # file based
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    # database-platform: org.hibernate.dialect.H2Dialect # Not requried
    defer-datasource-initialization: false # true, false if we use flyway or liquibase or schema.sql
  h2:
    console:
      enabled: false # override to true in local/dev env if desired

server:
  compression:
    enabled: true
    mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json"
    min-response-size: 2048
