spring:
  # config:
  #   import: optional:file:mysql-user-docker-secret,optional:configtree:/run/secrets/
  datasource: # We are expecting to use a docker container mysql instance
    platform: mysql
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/wrasslin-clips?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_USER_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # true, false if we use flyway or liquibase or schema.sql
    show-sql: true
    hibernate:
      ddl-auto: none # or create, create-drop, validate, none, update
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.MySQL8Dialect # It should auto-detect so this might be unnecessary
  sql:
    init:
      mode: always