-- CREATE ALIAS IF NOT EXISTS FTL_INIT FOR "org.h2.fulltext.FullTextLucene.init";
-- CALL FTL_INIT();
CREATE ALIAS IF NOT EXISTS FT_INIT FOR "org.h2.fulltext.FullText.init";
CALL FT_INIT();

CREATE TABLE VIDEO(ID INT PRIMARY KEY, URL VARCHAR, POSITION VARCHAR, FAMILY VARCHAR, TAGS VARCHAR, NOTES VARCHAR, RELATED VARCHAR);

-- CALL FTL_CREATE_INDEX('PUBLIC', 'VIDEO', NULL);
CALL FT_CREATE_INDEX('PUBLIC', 'VIDEO', NULL);
